### ISSUE TITLE
Did you start?

### ISSUE THREAD

**Issue by satvikmaker** [BaddMann/movieflaskpy#1]
Hello,

I'm pretty curious on this. Did you start? Would like to start or contribute to this project.

**Comment by BaddMann** [comment]
You go ahead. I couldn't get past the research part before my job pulled me in three different directions. Once things calm down again, I'd appreciate a leg up! 

Take a serious look at the beta project videogrep did. He had susseful implemented ffmpeg and python within an electron app for the macOS. A few changes and moviepy cold be injected! A few more changes and I think cross platform would be possible.

**Comment by satvikmaker** [comment]
Thank you for the suggestions and pointers. Will take a look at it.
